name: 'Build Docs'

on:
  push:
    branches:
      - 'main'
      - 'master'
  schedule:
    # rebuild docs at 10 AM every Monday
    - cron:  '0 10 * * 1'

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Show env
        run: 'env | sort -u'
      - name: Install Roswell
        env:
          LISP: sbcl-bin
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          echo /home/runner/.roswell/bin >> $GITHUB_PATH
      - name: Check CL Version
        run: |
          ros install 40ants/cl-info
          cl-info
      - name: Install Qlot
        run: ros install qlot
      - name: Install Dependencies
        run: |
          sudo apt-get install pandoc texi2html
          qlot install
      - name: Install Eazy Documentation fork
        # Because my patches aren't in the upstream yet:
        # https://github.com/guicho271828/eazy-documentation/pull/2
        run: |
          git clone git://github.com/svetlyak40wt/eazy-documentation.git .qlot/local-projects/eazy-documentation/
          cd .qlot/local-projects/eazy-documentation/
          git checkout replace-ignore-errors
          cd ../../../
      - name: Build docs
        run: qlot exec doc/scripts/build.ros
        env:
          # This token is automaticaly added to the secrets
          # by GitHub. Read more here:
          # https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
